### ISSUE TITLE
Image doesn't reload if src property changes

### ISSUE THREAD

**Issue by JaySunSyn** [hejty/image-mask#4]
If src property is set dynamically, the image doesn't display. 

Visit will be set from outside the element:

    <image-mask id="avatar" class="card-image" shape="circle"
      src="[[visit.image]]"
      size="50">
    </image-mask>
    .
    .
    .

    visit: {
          type: Object,
          value: function () { return {}; },
          notify: true
        }

**Comment by hejty** [comment]
@JaySunSyn check out a new release of image-mask element. I've added an observer method `srcChanged`, yay! :)
