### ISSUE TITLE
Placeholder loaded over http

### ISSUE THREAD

**Issue by JaySunSyn** [hejty/image-mask#6]
The placeholder http://placehold.it/320 is not loaded over SSL. 
This content should be served over HTTPS if you use SSL.

You could replace it with https://placehold.it/320 

Thanks for the element!

**Comment by hejty** [comment]
It's fixed now! I've also added a new shape for clipping your images - `squircle` (iOS app). Check it out.

**Comment by JaySunSyn** [comment]
Cool, thanks!!
