### ISSUE TITLE
Safari: NoModificationAllowedError: DOM Exception 7

### ISSUE THREAD

**Issue by JaySunSyn** [hejty/image-mask#7]
Thanks again for the element!
Check your demo on Safari, I get an error:
`NoModificationAllowedError: DOM Exception 7: An attempt was made to modify an object where modifications are not allowed.`

**Comment by hejty** [comment]
Fixed! Enjoy :)

**Comment by JaySunSyn** [comment]
Awesome!

**Comment by lxn07122945** [comment]
how ?
