### ISSUE TITLE
Hexagon mask is not working

### ISSUE THREAD

**Issue by Falconerd** [hejty/image-mask#9]
Hey, nice component. Just letting you know the hexagon mask isn't working for me.

I can't see it on the demo either: http://hejty.github.io/demos/image-mask/

__OS__
Elementary OS Freya (Ubuntu 14.04 LTS)

__Browsers__
Chrome Version 51.0.2704.54 beta (64-bit)
Firefox Version 46.0.1

**Comment by hejty** [comment]
Hey @Falconerd,

Thank you, there was a typo in the code. It's fixed now...
